FROM ubuntu:18.04
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update -q && apt-get install -qy \
      man make git netcat \
      software-properties-common

WORKDIR %WORKDIR%
VOLUME  /workdir
EXPOSE %EXPOSE%

# vim: ft=Dockerfile
